export const UPDATE_SELECT_MODE = 'UPDATE_SELECT_MODE'
export const UPDATE_SELECT_ALL_MODE = 'UPDATE_SELECT_ALL_MODE'
export const RENEWAL_LIST = 'RENEWAL_LIST'
export const FUNCTION_LIST = 'FUNCTION_LIST'
